// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alumpnbieclrvfnopjqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdW1wbmJpZWNscnZmbm9wanFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDg5NDgsImV4cCI6MjA2NzEyNDk0OH0.olx6m-wLrH2WRc_jWLGsmfnV_euPgDT9aHW9zj_01ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});